name: Node.js CI
on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable Yarn with Corepack
        run: corepack enable yarn

      - name: Install dependencies
        run: yarn install

      - name: Run lint and code analysis
        run: yarn run lint

      - name: Build project
        run: yarn run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            lib/**/*.js
            lib/**/*.js.map
            lib/**/*.d.ts
            test/**/*.js
            test/**/*.js.map

  test:

    runs-on: ubuntu-latest

    needs: build

    env:
      YARN_IGNORE_NODE: 1

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Yarn with Corepack
        run: corepack enable yarn

      - name: Install dependencies
        run: yarn install

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Test with Node.js ${{ matrix.node-version }}
        run: yarn run test-coverage

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.test_number }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Complete Coveralls parallel run
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
